modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://github.com/Minemobs/x/issues" #optional
[[mods]]
modId="minemobstemplate" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Minemobs Template" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="minemobstemplate.png" #optional
credits="" #optional
authors="minemobs" #optional
description='''
A template for minemobs's forge mods
'''
[[dependencies.minemobstemplate]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[36,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.minemobstemplate]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
